# -*- coding: utf-8 -*-
"""BMW.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kf_2hUg41reWwVhqjPwxcBax4VwO09oj
"""

import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import numpy as np
import seaborn as sns
from scipy.stats import pearsonr

#chargement des données
data = pd.read_csv("bmw_global_sales_2018_2025.csv")
data

#renommer les variables pour mieux comprendre
data = data.rename(columns={
    "Units_Sold": "Ventes",
    "Avg_Price_EUR": "Prix_Moyen",
    "Revenue_EUR": "Chiffre_Affaires",
    "BEV_Share": "Part_Electrique",
    "Premium_Share": "Part_Premium",
    "GDP_Growth": "Croissance_PIB",
    "Fuel_Price_Index": "Indice_Carburant"
})

data.info()

data.describe()

# valeurs manquantes
print(data.isnull().sum())

col_num = data.select_dtypes(include=[np.number]).columns

for col in col_num:
    fig = px.box(data, y=col, title=f"Boxplot de {col}")
    fig.show()

#calcul du  upper bound et lower bound pour les colonnes numeriques
# utilisation de numpy pour le calcul des quartiles
for col in col_num :
  Q1= np.percentile(data[col],25)
  Q3= np.percentile(data[col],75)
  IQR=Q3-Q1
  lower_bound=Q1-1.5*IQR
  upper_bound=Q3+1.5*IQR
  outliers=data[(data[col]<lower_bound) | (data[col]>upper_bound)]
  print(f"{col}:lower bound = {lower_bound}, upper bound = {upper_bound}")

#part des vehicules electriques negatifs
data[data["Part_Electrique"] < 0]

#part des vehicules electriques superieur a 1
data[data["Part_Electrique"] > 1]

#là on supprime les valeurs negatifs
data = data[data["Part_Electrique"] >= 0]

print(len(data))

#Boxplot des ventes par région
fig = px.box(data,x="Region",y="Ventes",color="Region",title="Distribution des ventes par région"
)
fig.show()

#Boxplot du revenu par modèl
fig = px.box(data,x="Model",y="Chiffre_Affaires",color="Model",title="Distribution du revenu  par modèle")
fig.show()

#Boxplot BEV (électrique) par région
fig = px.box(data,x="Region",y="Part_Electrique",color="Region",title="Distribution des parts électriques par région")
fig.show()

#Boxplot Premium par région
fig = px.box(data,x="Region",y="Part_Premium",color="Region",title="Distribution de Premium par région")
fig.show()

#correlation et heatmap
correlation = data.select_dtypes(include=[np.number]).corr()
fig = px.imshow(correlation,text_auto=True,color_continuous_scale='RdBu_r',
    title='Correlation Heatmap BMW')
fig.show()

#visualisation de la relation ventes et chiffres d'affaires en utilisant px.scatter
px.scatter(data, x="Ventes", y="Chiffre_Affaires",color="Chiffre_Affaires")

#evolution des ventes dans le temps
sales = data.groupby("Year")["Ventes"].sum().reset_index()

px.line(sales, x="Year", y="Ventes",title="Evolution des ventes BMW")

#evolution du chiffre d'affaire
revenue = data.groupby("Year")["Chiffre_Affaires"].sum().reset_index()

px.line(revenue, x="Year", y="Chiffre_Affaires",
        title="Evolution du chiffre d'affaires")

#evolution de la vente des voitures electriques
bev = data.groupby("Year")["Part_Electrique"].mean().reset_index()

px.line(bev, x="Year", y="Part_Electrique",title="Evolution des véhicules électriques")

#vente des vehicules premium
premium = data.groupby("Year")["Part_Premium"].mean().reset_index()

px.line(premium, x="Year", y="Part_Premium",
        title="Evolution du segment premium")

#chiffre d'affaire par region
data.groupby("Region")[["Ventes","Chiffre_Affaires"]].mean()

region_revenue = data.groupby("Region")["Chiffre_Affaires"].sum().reset_index()

px.bar(region_revenue, x="Region", y="Chiffre_Affaires",
       title="Chiffre d'affaires par région")

#part des vehicules electriques par region
data.groupby("Region")[["Ventes","Part_Electrique"]].mean()

region_bev = data.groupby("Region")["Part_Electrique"].mean().reset_index()

px.bar(region_bev, x="Region", y="Part_Electrique",
       title="Part électrique par région")

